name: SignFix
main: com.udonya.signfix.SignFix
version: 1.0.0
authors:
  - udonya
description: Sign input methods within command-line.
website: http://dev.bukkit.org/server-mods/signfix/
dev-url: https://github.com/udonya
commands:
  signfix:
    aliases: [signfix, sf]
    description: Provides a way to input text to sign with the command-line.
    usage: This is SignFix's command. See /sf help for more.
