name: SignFix
main: com.udonya.signfix.SignFix
version: 0.2
authors:
  - udonya
description: Sign input methods within command-line.
website: http://dev.bukkit.org/server-mods/signfix/
dev-url: https://github.com/udonya
commands:
  signfix:
    aliases: [signfix, sf]
    description: Set multilang character to a sign.
    usage: This is SignFix's command. See /sf help for more.
